name: Prettier
on:
  pull_request:
  push:
permissions:
  contents: read
  actions: read
jobs:
  prettier:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci && npx prettier -c .
